### ISSUE TITLE
Version 1.2 Bugged with Expansion Pack

### ISSUE THREAD

**Issue by CodebyRonin** [mikeyhoward1977/easy-plugin-demo#11]
Hey Mikey,
I updated to the newest version you released yesterday right before we launched our demo site. Unfortunately there now seems to be an incompatibility with the Expansions pack plugin as the cloning and other options disappear and an error occurs during a site cloning after using the form. 

PHP Fatal error:  Uncaught Error: Call to undefined function epd_get_default_site_option_keys() epd-premium/includes/clone/class-epdp-clone-site.php:322

If there there is an updated version of the expansion pack your EDD license key code is not showing the premiums update in the update area.

Let me know if you need more details.

I currently reverted back to the previous release.

Thanks

**Comment by mikeyhoward1977** [comment]
Apologies for this. We have just released an updated version of the premium pack which will ensure the EPD core plugin is at the required version to avoid such errors.
Regarding license keys, please visit [Your Account](https://easy-plugin-demo.com/your-account) to retrieve your license keys and add them to the premium pack via Settings -> Easy Plugin Demo -> Premium License. There is a premium pack update available which your site should pickup shortly. Alternatively you can download via the link above.

**Comment by CodebyRonin** [comment]
Thanks for quickly responding. I should have responded right back that I had gone to the Your Account page and downloaded 1.1 of the expansion back. It's 4:23am here in Florida but later when I wake up I will retest everything with fresh eyes. I may have found another but don't want to create and Issue until I test it again. Thanks for all of your help. We are definitely going to be promoting your plugin through our demo as users test out our plugins and extensions.

**Comment by mikeyhoward1977** [comment]
Thanks, appreciate it. We have updated both the core and premium pack plugin this morning. The issues you mentioned here should now be addressed... Get some sleep :)
