### ISSUE TITLE
Update/Reinstall causes all settings/options for EPD plugin to completely reset.

### ISSUE THREAD

**Issue by CodebyRonin** [mikeyhoward1977/easy-plugin-demo#12]
Not sure if this is intentional if it is I highly recommend giving the users of your plugin the ability to determine to delete the plugin settings for EPD before uninstalling at minimum and not make it delete the options set for the plugin by default.

**Comment by mikeyhoward1977** [comment]
This has been addressed with today's update. The option is under the **Misc** tab within the EPD Settings page and is honored for both the core plugin and the Premium Pack
