### ISSUE TITLE
Allow "Cloned Site" to be set to never expiring.

### ISSUE THREAD

**Issue by CodebyRonin** [mikeyhoward1977/easy-plugin-demo#14]
I made a sub-site demo that I want to be using as the "Clone Site" which is also set in the Premium Packs Cloning options. The problem it is set to expire at the time I set for the other demos. I am going to go into the database and clear out the row so it doesn't expire for now. I see you created a new Demos custom post type and I believe it would need to be done there also. 

You could also just allow the time to be changed in the Network Admin area under the sites tab to be changed to a different time that was Super Admin can extend or prevent users sites from expiring if needed. Not a bad idea especially for plugin developers like us who will most likely get people asking for support ect and we may need a day or so to help. We did set a long time for demo to expire for now. 

I looked into the Site-actions.php file in the plugin and noticed there is no exception for the the "Clone Site" and user to not be deleted.

**Comment by CodebyRonin** [comment]
Looking into this further. It appears as though the plugin needs an option to change "epd_site_expires" in the database table "blog_meta" for the demo site. Would be awesome if you could edit it in the Network Admin > Sites page which lists out the sites on the network.

**Comment by mikeyhoward1977** [comment]
Don't delete the 'epd_site_expires' key. Instead set it to 0. Per [epd_exclude_sites_from_delete()](https://github.com/mikeyhoward1977/easy-plugin-demo/blob/master/includes/sites/site-functions.php#L252) we search for the 0 for exclusions from the delete task.

Or, if preferred you can create a function and filter the [epd_delete_expired_sites_exclusions](https://github.com/mikeyhoward1977/easy-plugin-demo/blob/master/includes/sites/site-functions.php#L258) array and add the site ID('s) to the array.

I will be adding options to extend the lifetime of individual sites, and to exclude from deletion altogether.

**Comment by CodebyRonin** [comment]
Oh yea. I had actually just set it to 0. Don't want to break any functions searching or using that key. I had followed the functions on the admin-pages.php and figured it out. After I did so I did also find the filter and function. Just curious does the User still get deleted though? or does the filter prevent that from happening also.

Thanks for responding quickly! I left you a stellar .org review on the free plugin. We already have a backlog of potential users in our support system ready to try out our demo.

**Comment by mikeyhoward1977** [comment]
If the site is not deleted, the user is not deleted. We check that users do not have any active sites before we delete so setting that key to 0 (and therefore not deleting the site) will prevent the user being deleted.

The "Clone Master" will be excluded from the delete process from the next release (including clones defined within Demo Templates)

Thanks so much for the review 👍 Much appreciated

**Comment by CodebyRonin** [comment]
Awesome! That makes sense 🤙  No problem you have been super helpful! Saw you forked Give plugin at one point. Have talked to Matt Cromwell through the years. We always talk with those guys at WordCamp Miami every year. I realize this isn't the place to have this conversation just thought I would mention it. My brother and I always get stoked to meet/talk with other WP Plugin devs.

**Comment by mikeyhoward1977** [comment]
Just to update... Clone sites, including those defined to be cloned from within Demo Templates will be excluded from the expire (deletion process) from the next release. Users also maintained.

Was always planning on allowing super admins to extend a sites lifetime. Logical place to put this option is within the Info tab on the Edit Site screen, however would you believe... there are no hooks on that page! I did create a PR/patch but its not been touched since so not expecting anytime soon.

We'll just add the option elsewhere for now
