### ISSUE TITLE
Please someone revive this remarkable plugin!

### ISSUE THREAD

**Issue by Zurqui** [mikeyhoward1977/easy-plugin-demo#37]
It is incredibly disappointing that a plugin as complex and remarkable as this one is suddenly abandoned. Those of us who purchased the premium version are left unsupported and adrift. My project relied heavily on this plugin premium version, and now I am in serious trouble as the plugin has started to fail with the latest WordPress updates. The premium version component of the plugin made it truly unique, it was the only plugin capable of cloning a multisite network site, just from outside the network, from another remote site via an API connection.

If there are any developers interested in revitalizing this remarkable plugin and continuing to update and maintain it, I will be happy to provide all the code including the component "EPD remote", that the premium version offered. The plugin is worth it and for sure whoever rescues it from abandonment will get great benefits.

**Comment by Zurqui** [comment]
Message in a bottle: If there’s any developer who wants to rebrand this dead plugin and give it a new life, just follow this link (https://join.slack.com/t/newworkspace-hfu8652/shared_invite/zt-26jh2b4a8-vfj9rf7iFgMPRcY8L3pYZQ), and I will share the whole code and documentation I have, including its premium version. I’m not expecting anything in return, just to have a new version of this plugin back on the WordPress repository. And if you are a smart developer and manage reviving this plugin, you will discover its potential as a competitor on the plugin’s market. Actually there is only one plugin for generating demo sites (Demo Builder from Motopress), and I can tell you, Easy Plugin Demo was even better and more powerful.

**Comment by mhimon** [comment]
hey @mikeyhoward1977 
I want to rebuild the plugin. Can we talk?

email: imon@ultradevs.com

Thanks
