### ISSUE TITLE
is_network_admin Notice

### ISSUE THREAD

**Issue by CodebyRonin** [mikeyhoward1977/easy-plugin-demo#7]
Receiving a php notice when plugin is activated. _Notice: Use of undefined constant is_network_admin - assumed 'is_network_admin'_

on lines 269 and 300 of easy-plugin-demo/easy-plugin-demo.php

I understand this is just a notice but I believe in future versions of PHP this will be thrown as an error.

**Comment by mikeyhoward1977** [comment]
Thanks. This issue is addressed in the upcoming v1.2. I'll leave open until the release is pushed

**Comment by CodebyRonin** [comment]
@mikeyhoward1977 Awesome! Thanks so much for your awesome plugin. Almost done setting it up here. Will be turning on the "Give Credit" checkbox. Need to get you to 100 active installs as even when I searched your plugin name exactly in the .org repository you aren't showing up yet.
